# Generated by Django 5.2.16 on 2026-07-13 09:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


def backfill_user_roles(apps, schema_editor):
    UserAccount = apps.get_model("accounts", "UserAccount")
    UserRole = apps.get_model("accounts", "UserRole")

    seen_assignments = set()
    duplicate_ids = []

    for assignment in UserRole.objects.order_by("user_id", "role_id", "assigned_at", "id"):
        key = (assignment.user_id, assignment.role_id)
        if key in seen_assignments:
            duplicate_ids.append(assignment.id)
            continue
        seen_assignments.add(key)

    if duplicate_ids:
        UserRole.objects.filter(id__in=duplicate_ids).delete()

    for user in UserAccount.objects.exclude(role_id__isnull=True).iterator():
        UserRole.objects.get_or_create(
            user_id=user.id,
            role_id=user.role_id,
            defaults={"assigned_by_id": None},
        )


def noop_reverse(apps, schema_editor):
    """No-op reverse."""


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRoleScope',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scope_type', models.CharField(max_length=100)),
                ('scope_id', models.UUIDField()),
            ],
        ),
        migrations.AddConstraint(
            model_name='role',
            constraint=models.UniqueConstraint(fields=('company', 'name'), name='unique_role_name_per_company'),
        ),
        migrations.RunPython(backfill_user_roles, noop_reverse),
        migrations.AddConstraint(
            model_name='userrole',
            constraint=models.UniqueConstraint(fields=('user', 'role'), name='unique_user_role_assignment'),
        ),
        migrations.AddField(
            model_name='userrolescope',
            name='user_role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scopes', to='accounts.userrole'),
        ),
        migrations.AddConstraint(
            model_name='userrolescope',
            constraint=models.UniqueConstraint(fields=('user_role', 'scope_type', 'scope_id'), name='unique_user_role_scope_row'),
        ),
    ]
