# Generated by Django 5.2.16 on 2026-07-14

from django.db import migrations


PERMISSION_SPECS = (
    ("users.view", "View users", "Users", "Allows a tenant role to view users."),
    ("users.create", "Create users", "Users", "Allows a tenant role to create users."),
    ("users.edit", "Edit users", "Users", "Allows a tenant role to edit users."),
    ("users.update", "Update users", "Users", "Allows a tenant role to update users."),
    ("roles.view", "View roles", "Roles", "Allows a tenant role to view roles."),
    ("roles.create", "Create roles", "Roles", "Allows a tenant role to create roles."),
    ("roles.edit", "Edit roles", "Roles", "Allows a tenant role to edit roles."),
    ("roles.update", "Update roles", "Roles", "Allows a tenant role to update roles."),
    (
        "departments.view",
        "View departments",
        "Departments",
        "Allows a tenant role to view departments.",
    ),
    (
        "departments.create",
        "Create departments",
        "Departments",
        "Allows a tenant role to create departments.",
    ),
    (
        "departments.edit",
        "Edit departments",
        "Departments",
        "Allows a tenant role to edit departments.",
    ),
    (
        "departments.update",
        "Update departments",
        "Departments",
        "Allows a tenant role to update departments.",
    ),
    (
        "organization_units.view",
        "View organization units",
        "Organization Units",
        "Allows a tenant role to view organization units.",
    ),
    (
        "organization_units.create",
        "Create organization units",
        "Organization Units",
        "Allows a tenant role to create organization units.",
    ),
    (
        "organization_units.edit",
        "Edit organization units",
        "Organization Units",
        "Allows a tenant role to edit organization units.",
    ),
    (
        "organization_units.update",
        "Update organization units",
        "Organization Units",
        "Allows a tenant role to update organization units.",
    ),
    (
        "facilities.view",
        "View facilities",
        "Facilities",
        "Allows a tenant role to view facilities.",
    ),
    (
        "facilities.create",
        "Create facilities",
        "Facilities",
        "Allows a tenant role to create facilities.",
    ),
    (
        "facilities.edit",
        "Edit facilities",
        "Facilities",
        "Allows a tenant role to edit facilities.",
    ),
    (
        "facilities.update",
        "Update facilities",
        "Facilities",
        "Allows a tenant role to update facilities.",
    ),
)


def seed_canonical_permissions(apps, schema_editor):
    Permission = apps.get_model("accounts", "Permission")
    for code, name, module, description in PERMISSION_SPECS:
        Permission.objects.using(schema_editor.connection.alias).update_or_create(
            code=code,
            defaults={
                "name": name,
                "module": module,
                "description": description,
            },
        )


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_remove_useraccount_role_and_legacy_rbac_models"),
    ]

    operations = [
        migrations.RunPython(
            seed_canonical_permissions,
            migrations.RunPython.noop,
        ),
    ]
